name: New FXserver version released
on:
  workflow_dispatch:
    inputs:
      optional:
        description: 'new optional version'
        required: false
      optional_url:
        description: 'optional version url'
        required: false
      recommended:
        description: 'new recommended version'
        required: false
      recommended_url:
        description: 'recommended version url'
        required: false
jobs:
  update-all:
    name: Update All
    runs-on: ubuntu-latest
    if: github.event.inputs.recommended == github.event.inputs.optional
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update Dockerfile
      run: perl -i -pe 's,(?<=curl ).*(?= \|),${{ github.event.inputs.recommended_url }},' Dockerfile
    - name: Commit Dockerfile
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "[Auto] New FXServer recommended & optional version: ${{ github.event.inputs.recommended }}" -a
    - uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag: ${{ github.event.inputs.recommended }}
    - name: Create tag
      if: steps.checkTag.outputs.exists == 'false'
      run: git tag ${{ github.event.inputs.recommended }}
    - name: Push new branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: ${{ github.event.inputs.recommended }}
        github_token: ${{ github.token }}
        tags: true
    - name: Create optional PR
      uses: peter-evans/create-pull-request@v3
      with:
        branch: optional
        delete-branch: false
        base: ${{ github.event.inputs.optional }}
        title: '[Auto] New FXServer optional version: ${{ github.event.inputs.optional }}'
        body: ''
        assignees: routmoute
    - name: Create recommended PR
      uses: peter-evans/create-pull-request@v3
      with:
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        branch: main
        delete-branch: true
        base: ${{ github.event.inputs.recommended }}
        title: '[Auto] New FXServer recommended version: ${{ github.event.inputs.recommended }}'
        body: ''
        assignees: routmoute

  update-optional:
    name: Update Optional
    runs-on: ubuntu-latest
    needs: update-all
    if: github.event.inputs.optional && needs.update-all.result == 'skipped'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update Dockerfile
      run: perl -i -pe 's,(?<=curl ).*(?= \|),${{ github.event.inputs.optional_url }},' Dockerfile
    - name: Commit Dockerfile
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "[Auto] New FXServer optional version: ${{ github.event.inputs.optional }}" -a
    - uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag: ${{ github.event.inputs.optional }}
    - name: Create tag
      if: steps.checkTag.outputs.exists == 'false'
      run: git tag ${{ github.event.inputs.optional }}
    - name: Push new branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.event.inputs.optional }}
        tags: true
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        branch: optional
        delete-branch: true
        base: ${{ github.event.inputs.optional }}
        title: '[Auto] New FXServer optional version: ${{ github.event.inputs.optional }}'
        body: ''
        assignees: routmoute

  update-recommended:
    name: Update Recommended
    runs-on: ubuntu-latest
    needs: update-all
    if: github.event.inputs.recommended && needs.update-all.result == 'skipped'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Modify Dockerfile
      run: perl -i -pe 's,(?<=curl ).*(?= \|),${{ github.event.inputs.recommended_url }},' Dockerfile
    - name: Commit Dockerfile
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "[Auto] New FXServer recommended version: ${{ github.event.inputs.recommended }}" -a
    - uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag: ${{ github.event.inputs.recommended }}
    - name: Create tag
      if: steps.checkTag.outputs.exists == 'false'
      run: git tag ${{ github.event.inputs.recommended }}
    - name: Push new branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.event.inputs.recommended }}
        tags: true
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        branch: main
        delete-branch: true
        base: ${{ github.event.inputs.recommended }}
        title: '[Auto] New FXServer recommended version: ${{ github.event.inputs.recommended }}'
        body: ''
        assignees: routmoute
